client_config_backend: file
client_config_file: client_secrets.json
# client_config:
  # client_id: jibberjabber
  # client_secret: yourmothersadirtywhore

save_credentials: True
save_credentials_backend: file
save_credentials_file: google_creds.txt

get_refresh_token: True

oauth_scope:
  - https://www.googleapis.com/auth/drive