from ..util.settings import Settings

from ..util.urls import ONLYFANS_HOME_URL, ONLYFANS_SETTINGS_URL, ONLYFANS_CHAT_URL, ONLYFANS_NEW_MESSAGE_URL, ONLYFANS_HOME_URL2, ONLYFANS_USERS_ACTIVE_URL, ONLYFANS_USERS_FOLLOWING_URL